# Generated by Django 3.1.3 on 2020-11-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
